services:
  postgres_auth:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: authdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata_auth:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d authdb"]
      interval: 5s
      timeout: 3s
      retries: 5

  postgres_workout:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: workoutdb
    ports:
      - "5433:5432"
    volumes:
      - pgdata_workout:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d workoutdb"]
      interval: 5s
      timeout: 3s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  auth:
    build:
      context: .
      dockerfile: services/auth/Dockerfile
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: "postgres://admin:secret@postgres_auth:5432/authdb?sslmode=disable"
      JWT_SECRET: "my-super-secret-key"
      HTTP_PORT: "8080"
      JWT_ACCESS_TTL: "15m"
      JWT_REFRESH_TTL: "72h"
    depends_on:
      postgres_auth:
        condition: service_healthy

  workout:
    build:
      context: .
      dockerfile: services/workout/Dockerfile
    ports:
      - "8081:8081"
    environment:
      DATABASE_URL: "postgres://admin:secret@postgres_workout:5432/workoutdb?sslmode=disable"
      JWT_SECRET: "my-super-secret-key"
      HTTP_PORT: "8081"
      REDIS_ADDR: "redis:6379"
    depends_on:
      postgres_workout:
        condition: service_healthy
      redis:
        condition: service_healthy

volumes:
  pgdata_auth:
  pgdata_workout:
  redisdata: