INSERT INTO available_exercises (name, muscle_group, category) VALUES
('Приседания со штангой', 'Legs', 'compound'),
('Жим лёжа', 'Chest', 'compound'),
('Становая тяга', 'Back', 'compound'),
('Жим над головой', 'Shoulders', 'compound'),
('Тяга штанги в наклоне', 'Back', 'compound'),
('Подтягивания', 'Back', 'compound'),
('Румынская тяга', 'Legs', 'compound'),
('Жим гантелей', 'Chest', 'compound'),
('Разведение гантелей', 'Chest', 'isolation'),
('Сгибания рук с гантелями', 'Arms', 'isolation'),
('Французский жим', 'Arms', 'isolation'),
('Подъём на бицепс', 'Arms', 'isolation'),
('Жим ногами', 'Legs', 'compound'),
('Разгибание ног', 'Legs', 'isolation'),
('Сгибание ног', 'Legs', 'isolation'),
('Планка', 'Core', 'isolation'),
('Велосипед', 'Cardio', 'cardio'),
('Беговая дорожка', 'Cardio', 'cardio');