global:

templates:
  - "/etc/alertmanager/templates/*.tmpl"

route:
  receiver: default

  group_by:
    - alertname
    - service

  group_wait: 10s
  group_interval: 30s
  repeat_interval: 1h

  routes:
    - matchers:
        - severity="critical"
      receiver: telegram-critical

    - matchers:
        - severity="warning"
      receiver: telegram-warning

receivers:
  - name: default

  - name: telegram-critical
    telegram_configs:
      - bot_token_file: /run/secrets/telegram_bot_token
        chat_id_file: /run/secrets/telegram_chat_id
        send_resolved: true
        parse_mode: ""
        message: '{{ template "telegram.fitness.message" . }}'

  - name: telegram-warning
    telegram_configs:
      - bot_token_file: /run/secrets/telegram_bot_token
        chat_id_file: /run/secrets/telegram_chat_id
        send_resolved: true
        parse_mode: ""
        message: '{{ template "telegram.fitness.message" . }}'

inhibit_rules:
  - source_matchers:
      - severity="critical"

    target_matchers:
      - severity="warning"

    equal:
      - service